config/routes.rb
Rails.application.routes.draw do
  root 'tanques#index'
  resources :tanques
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tanque.rb
class Tanque < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tanques_controller.rb
class TanquesController < ApplicationController
  before_action :set_tanque, only: [:show, :edit, :update, :destroy]

  # GET /tanques
  # GET /tanques.json
  def index
    @tanques = Tanque.all
  end

  # GET /tanques/1
  # GET /tanques/1.json
  def show
  end

  # GET /tanques/new
  def new
    @tanque = Tanque.new
  end

  # GET /tanques/1/edit
  def edit
  end

  # POST /tanques
  # POST /tanques.json
  def create
    @tanque = Tanque.new(tanque_params)

    respond_to do |format|
      if @tanque.save
        format.html { redirect_to @tanque, notice: "#{@tanque.nombre} fue creado exitosamente." }
        format.json { render :show, status: :created, location: @tanque }
      else
        format.html { render :new }
        format.json { render json: @tanque.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tanques/1
  # PATCH/PUT /tanques/1.json
  def update
    respond_to do |format|
      if @tanque.update(tanque_params)
        format.html { redirect_to @tanque, notice: 'Tanque was successfully updated.' }
        format.json { render :show, status: :ok, location: @tanque }
      else
        format.html { render :edit }
        format.json { render json: @tanque.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tanques/1
  # DELETE /tanques/1.json
  def destroy
    @tanque.destroy
    respond_to do |format|
      format.html { redirect_to tanques_url, notice: 'Tanque was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tanque
      @tanque = Tanque.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tanque_params
      params.require(:tanque).permit(:nombre, :caracteristicas)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tanques_helper.rb
module TanquesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Servidor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tanques/_form.html.erb
<%= form_with(model: tanque, local: true) do |form| %>
  <% if tanque.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tanque.errors.count, "error") %> error al tratar de guardar este tanque:</h2>

      <ul>
      <% tanque.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :caracteristicas %>
    <%= form.text_area :caracteristicas %>
  </div>

  <div class="actions">
    <%= form.submit "Crear Tanque" %>
  </div>
<% end %>

app/views/tanques/edit.html.erb
<h1>Editando Tanque</h1>

<%= render 'form', tanque: @tanque %>

<%= link_to 'Ver', @tanque %> |
<%= link_to 'Atrás', tanques_path %>

app/views/tanques/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tanques</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Caracteristicas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tanques.each do |tanque| %>
      <tr>
        <td><%= tanque.nombre %></td>
        <td><%= tanque.caracteristicas %></td>
        <td><%= link_to 'Ver', tanque %></td>
        <td><%= link_to 'Editar', edit_tanque_path(tanque) %></td>
        <td><%= link_to 'Eliminar', tanque, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Tanque', new_tanque_path %>

app/views/tanques/new.html.erb
<h1>Nuevo Tanque</h1>

<%= render 'form', tanque: @tanque %>

<%= link_to 'Atrás', tanques_path %>

app/views/tanques/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @tanque.nombre %>
</p>

<p>
  <strong>Caracteristicas:</strong>
  <%= @tanque.caracteristicas %>
</p>

<%= link_to 'Editar', edit_tanque_path(@tanque) %> |
<%= link_to 'Atrás', tanques_path %>